opc-ua:
  server:
    endpoint: opc.tcp://10.177.241.72:49320
    security-policy: none
    username: OPCUA
    password: 123456
  client:
    name-space: 2
    application-name: OpcUaClientPool
    application-uri: urn:yst:client-pool
    request-timeout-millis: 60000
  pool:
      core-size: 20
      max-size: 80
      max-idle-minutes: 5
      cleanup-interval-minutes: 5
http-server:
    port: 6111
    read-url:
    write-url: