opc-ua:
  server:
    endpoint: opc.tcp://10.177.241.72:49320
    security-policy: none
    username: OPCUA
    password: 123456
  client:
    namespace: 2
    application-name: OpcUaClientPool
    application-uri: urn:yst:client-pool
    request-timeout-millis: 60000
    hot-data:
      hot-data-check-window-minutes: 1
      hot-data-threshold: 1
  pool:
      core-size: 4
      max-size: 8
      max-idle-minutes: 5
      cleanup-interval-minutes: 5
      borrow-timeout-millis: 60000
      subscribe-core-size: 4
http-server:
    port: 6111
    read-url: /App/Get
    write-url: /App/Set